// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC12dvsRVSpjw9wFtstHqmI8VItQCSk_Vg',
    appId: '1:745722693020:web:d57219310ad3802f167459',
    messagingSenderId: '745722693020',
    projectId: 'flutterdu13',
    authDomain: 'flutterdu13.firebaseapp.com',
    storageBucket: 'flutterdu13.appspot.com',
    measurementId: 'G-HGJQD75X48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1LOUC1Bu3aDjpoHHjob48TLtWyyFLTpo',
    appId: '1:745722693020:android:03e32270ab931e8d167459',
    messagingSenderId: '745722693020',
    projectId: 'flutterdu13',
    storageBucket: 'flutterdu13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvMfuIsScrg0gYQp45eD8GPomw1f_q4aI',
    appId: '1:745722693020:ios:4272ea274dfa62cf167459',
    messagingSenderId: '745722693020',
    projectId: 'flutterdu13',
    storageBucket: 'flutterdu13.appspot.com',
    iosClientId: '745722693020-jqcq5c96mntbc89uvlt6mf5uhi5qtjm8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDu13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvMfuIsScrg0gYQp45eD8GPomw1f_q4aI',
    appId: '1:745722693020:ios:4272ea274dfa62cf167459',
    messagingSenderId: '745722693020',
    projectId: 'flutterdu13',
    storageBucket: 'flutterdu13.appspot.com',
    iosClientId: '745722693020-jqcq5c96mntbc89uvlt6mf5uhi5qtjm8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDu13',
  );
}
